package com.gxkzw.gx.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("auth_code", "id", AuthCode.class);
		arp.addMapping("certi", "id", Certi.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_info", "id", OrderInfo.class);
		arp.addMapping("price", "id", Price.class);
		arp.addMapping("session", "id", Session.class);
	}
}

