package com.gxkzw.gx.common.model;

import com.gxkzw.gx.common.model.base.BaseOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	
}
