package com.gxkzw.gx.common.model;

import com.gxkzw.gx.common.model.base.BasePrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Price extends BasePrice<Price> {
	
	/*
	 * 考证类型分为:1:笔试,2:面试,0:默认
	 */
	public static final int KZ_TYPE_DEFAULT = 0; 
	public static final int KZ_TYPE_WRITTEN = 1;
	public static final int KZ_TYPE_INTERVIEW = 2;
	
	/*
	 * 培训班类型:0:默认 1:全程班 2:冲刺班 3:定制班
	 */
	public static final int TRAIN_TYPE_DEFAULT = 0;
	public static final int TRAIN_TYPE_QUAN = 1;
	public static final int TRAIN_TYPE_CHONG = 2;
	public static final int TRAIN_TYPE_DING = 3;
}
