package com.gxkzw.gx.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderInfo<M extends BaseOrderInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
	}

	public java.lang.String getOrderId() {
		return get("orderId");
	}

	public void setCertiId(java.lang.Integer certiId) {
		set("certiId", certiId);
	}

	public java.lang.Integer getCertiId() {
		return get("certiId");
	}

	public void setEName(java.lang.String eName) {
		set("eName", eName);
	}

	public java.lang.String getEName() {
		return get("eName");
	}

	public void setEGender(java.lang.String eGender) {
		set("eGender", eGender);
	}

	public java.lang.String getEGender() {
		return get("eGender");
	}

	public void setEAge(java.lang.String eAge) {
		set("eAge", eAge);
	}

	public java.lang.String getEAge() {
		return get("eAge");
	}

	public void setEIdNumber(java.lang.String eIdNumber) {
		set("eIdNumber", eIdNumber);
	}

	public java.lang.String getEIdNumber() {
		return get("eIdNumber");
	}

	public void setEPhone(java.lang.String ePhone) {
		set("ePhone", ePhone);
	}

	public java.lang.String getEPhone() {
		return get("ePhone");
	}

	public void setEQQ(java.lang.String eQQ) {
		set("eQQ", eQQ);
	}

	public java.lang.String getEQQ() {
		return get("eQQ");
	}

	public void setEAddr(java.lang.String eAddr) {
		set("eAddr", eAddr);
	}

	public java.lang.String getEAddr() {
		return get("eAddr");
	}

	public void setEKzLevel(java.lang.String eKzLevel) {
		set("eKzLevel", eKzLevel);
	}

	public java.lang.String getEKzLevel() {
		return get("eKzLevel");
	}

	public void setEKzCourse(java.lang.String eKzCourse) {
		set("eKzCourse", eKzCourse);
	}

	public java.lang.String getEKzCourse() {
		return get("eKzCourse");
	}

	public void setEKzType(java.lang.String eKzType) {
		set("eKzType", eKzType);
	}

	public java.lang.String getEKzType() {
		return get("eKzType");
	}

	public void setEKzProject(java.lang.String eKzProject) {
		set("eKzProject", eKzProject);
	}

	public java.lang.String getEKzProject() {
		return get("eKzProject");
	}

}
