package com.gxkzw.gx.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrice<M extends BasePrice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKzType(java.lang.Integer kzType) {
		set("kzType", kzType);
	}

	public java.lang.Integer getKzType() {
		return get("kzType");
	}

	public void setExam(java.lang.Float exam) {
		set("exam", exam);
	}

	public java.lang.Float getExam() {
		return get("exam");
	}

	public void setTrain(java.lang.Float train) {
		set("train", train);
	}

	public java.lang.Float getTrain() {
		return get("train");
	}

	public void setMaterial(java.lang.Float material) {
		set("material", material);
	}

	public java.lang.Float getMaterial() {
		return get("material");
	}

	public void setCertiId(java.lang.Integer certiId) {
		set("certiId", certiId);
	}

	public java.lang.Integer getCertiId() {
		return get("certiId");
	}

	public void setMerge(java.lang.Float merge) {
		set("merge", merge);
	}

	public java.lang.Float getMerge() {
		return get("merge");
	}

	public void setTrainType(java.lang.Integer trainType) {
		set("trainType", trainType);
	}

	public java.lang.Integer getTrainType() {
		return get("trainType");
	}

	public void setDescri(java.lang.String descri) {
		set("descri", descri);
	}

	public java.lang.String getDescri() {
		return get("descri");
	}

}
